### ISSUE TITLE
About the job can not get the skill and abj of sjob over level 37！！

### ISSUE THREAD

**Issue by Freetate** [DerpyProjectGroup/topaz#1148]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
![01](https://user-images.githubusercontent.com/89332550/147719979-3dec6264-2c88-4bf8-8020-4b4d823f8197.png)
![01-1](https://user-images.githubusercontent.com/89332550/147719980-f6111466-0f3f-4780-8b45-9dd2b1907cc2.jpg)
![02](https://user-images.githubusercontent.com/89332550/147719992-546ca2c9-e12e-46c1-bc55-4c034f191ead.jpg)
![02-2](https://user-images.githubusercontent.com/89332550/147719993-e68c052c-094f-4d7a-97be-98b9107feb81.jpg)

im setting map.conf 
```
# Modify ratio of subjob-to-mainjob
# 0 = no subjobs
# 1 = 1/2   (default, 75/37, 99/49)
# 2 = 2/3   (75/50, 99/66)
# 3 = equal (75/75, 99/99)
subjob_ratio: 3
```

get 75/75 in game , but

When my main occupation is WHM75, I cannot get the abilities that sjob RDM 75 should have

When my main occupation is RDM 75, I cannot get the abilities that sjob WHM 75 should have

**Comment by almuth150** [comment]
These so-called stance abilities are not available when subbed on retail. Example, a level 99 RDM/WHM would not have access to Afflatus Solace/Misery despite those being available at 40 WHM. I believe Composure is also supposed to be excluded when RDM is subbed with that new retail thing that let people get up to 99/53.

Now, if there are other abilities that you should be granted that are being excluded, that would be a problem.

https://www.bg-wiki.com/ffxi/Afflatus_Solace On that page, it says "Not available via support job."

**Comment by TeoTwawki** [comment]
> These so-called stance abilities are not available when subbed on retail.  

Correct but we hadn't even implemented the restricting yet in LSB. Suspicion is there is some non LSB code or a client side restriction that did this, but I have not sat down to log in and look yet because I am at my day job currently. Asked him to make the issue last night so I'd remember to look.

**Comment by TeoTwawki** [comment]
So after some tinkering, it appears SE has added client side restrictions on what will appear. For years there were zero restrictions, you could put astral flow on a warrior if you coded the server to do it. For whatever reason they now prevent afflatus in the client unless mainjob is whm. I set my sub to 99 and was able to get abilities that happen later on past afflatus. I also verified we have nothing server side that would stop afflatus. While looking at this I realized there was one other JA that must be client restricted: call wyvern. Because I could not find any code anywhere server side blocking anything except 2hrs (which are now 1hr, but we're all used to calling them that).

**Comment by TeoTwawki** [comment]
@Freetate 它是一个客户端程序，FFXI 本身，它正在阻止 Afflatus  :cry:
