### ISSUE TITLE
Elevator NPC OnTrigger Crash in Grand Palace of HuXzoi

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#1150]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I'm not going to complain about the new players i've been getting, but more players = more crashes (for me anyways)....
I honestly don't know how to reproduce this... this is the feedback from one of my players though:
![image](https://user-images.githubusercontent.com/65316697/147825522-5da3cb73-8cef-4936-88a7-9f33c74f12ce.png)

Here is the link to my debug trace

https://wetransfer.com/downloads/4461ef1a86dc41c6e3273e51dc22e90b20211231132334/72bc75cd4b528abdfbd270fd835e198720211231132347/ad7f58

TIA

**Comment by zach2good** [comment]
`New Influx of players... More crashes...` - nothing helpful about this title, nothing searchable for anyone else who might encounter this crash in the future.

We've told you in the past that if we want a crash dump, we'll ask you for a crash dump:
https://github.com/LandSandBoat/server/issues/494#issuecomment-879898340

Have you looked to see if this is the same kind of crash as the ones before?
Have you inspected the dump file yourself?
Have you tried to reproduce the crash locally?
Why did you opt to dump a 400mb file instead of the 20 line crash dump that was produced by this crash?

This is the last time I'll open a crash dump that I didn't ask for.

Call stack::
```
 	VCRUNTIME140.dll!00007fffa47e15d8()	Unknown	Non-user code. Symbol loading disabled by Include/Exclude setting.
 	[Inline Frame] topaz_game_64.exe!std::_Char_traits<char,int>::move(char * const) Line 122	C++	Non-user code. Symbols loaded.
 	topaz_game_64.exe!std::string::assign(const char * const _Ptr=0x0000019975b59c90, const unsigned __int64 _Count=50) Line 3250	C++	Non-user code. Symbols loaded.
 	[Inline Frame] topaz_game_64.exe!std::string::_Copy_assign(const std::string &) Line 3035	C++	Symbols loaded.
 	[Inline Frame] topaz_game_64.exe!std::string::operator=(const std::string &) Line 3078	C++	Symbols loaded.
>	topaz_game_64.exe!luautils::OnTrigger(CCharEntity * PChar=0x0000019971264d00, CBaseEntity * PNpc=0x000001993e0839c0) Line 1856	C++	Symbols loaded.
 	topaz_game_64.exe!CAIContainer::Trigger(CCharEntity * player=0x0000019971264d00) Line 139	C++	Symbols loaded.
 	topaz_game_64.exe!SmallPacket0x01A(map_session_data_t * const PSession=0x000000000000000e, CCharEntity * const PChar=0x0000019971264d00, CBasicPacket data={...}) Line 755	C++	Symbols loaded.
 	topaz_game_64.exe!parse(char * buff=0x00000199757f69e0, unsigned __int64 * buffsize=0x0000001fa496de88, sockaddr_in * map_session_data=0x0000019971dca2d0, map_session_data_t *) Line 659	C++	Symbols loaded.
 	topaz_game_64.exe!do_sockets(fd_set * rfd, std::chrono::duration<__int64,std::ratio<1,10000000>> next) Line 416	C++	Symbols loaded.
 	topaz_game_64.exe!main(int argc=1, char * * argv=0x00000199210122a0) Line 495	C++	Symbols loaded.
 	[Inline Frame] topaz_game_64.exe!invoke_main() Line 78	C++	Non-user code. Symbols loaded.
 	topaz_game_64.exe!__scrt_common_main_seh() Line 288	C++	Non-user code. Symbols loaded.
 	kernel32.dll!00007fffaba17974()	Unknown	Non-user code. Symbol loading disabled by Include/Exclude setting.
 	ntdll.dll!00007fffae66a2f1()	Unknown	Non-user code. Symbol loading disabled by Include/Exclude setting.
```

The dump shows "Goodgravy" interacting with NPC "_1e1" in Aht Urghan Whitegate, crashing on this line:
```cpp
        PChar->StatusEffectContainer->DelStatusEffect(EFFECT_BOOST);
```

EDIT: "_1e1" is:
```sql
INSERT INTO `npc_list` VALUES (16982155,'_1e1','Salaheem\'s Sentinels',0,24.000,-7.298,-60.674,1,40,40,9,0,0,0,4099,0x0200000000000000000000000000000000000000,0,'TOAU',0);
```

**Comment by CatsEyeXI** [comment]
>Have you looked to see if this is the same kind of crash as the ones before?   
Yes

>Have you inspected the dump file yourself?   
I did my best, not really sure what im looking at, but I'm learning.  Clearly I was off and this was npc related and with a completely different player.

>Have you tried to reproduce the crash locally? 
I've tried to reproduce this for days. Even on my prod server.

>Why did you opt to dump a 400mb file instead of the 20 line crash dump that was produced by this crash?
Because one of the contributors suggested it.

Sorry about the subject line... I'll try to make it as relevant as possible in the future.

**Comment by CatsEyeXI** [comment]
>This is the last time I'll open a crash dump that I didn't ask for.

Did you bother to check if i was asked for one before being rude to me?

**Comment by TeoTwawki** [comment]
I take responsibility for the confusion and frustration regarding the crashdump.

@zach2good there is no harm in it being attached to the post even if you don't need/use it. I wanted to see one for that last one he posted to a closed issue regarding [CharEntity ](https://github.com/LandSandBoat/server/issues/652#issuecomment-1002353402)since the log had virtually nothing to work with.~~ It looks like this one is the preceding one with NPC entity.~~ **_nope its a whole new one that I can't repro. That npc is the door to the sentinels office, and both it and removing boost are just fine on stock repo._** There were different crashes he had posted but he didn't realize they weren't the same.
