### ISSUE TITLE
[AF] PLD boots quest A Boy's Dream not progressing

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#1156]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This quest used to work. Now we have a player who is on the step of giving the Odontosaurus item to Zaldon. He doesn't take it.
I went thru every single step several times with him. I also checked his var 'aBoysDreamCS' and it stay on 3.
He didn't have the quest "Under the Sea" flagged or finished.

https://github.com/LandSandBoat/server/blob/base/scripts/zones/Northern_San_dOria/npcs/Ailbeche.lua
https://github.com/LandSandBoat/server/blob/base/scripts/zones/Selbina/npcs/Zaldon.lua

**Comment by TeoTwawki** [comment]
Ah yes, a boy's nightmare. Confusing players since 2004.

That cs requires the player already have that variable with a value of 5, not 3, [so he's missing steps prior to this NPC which you can see here.](https://github.com/LandSandBoat/server/blob/2dbae3a1d7e3de544670f35051620660d5f9205f/scripts/zones/Northern_San_dOria/npcs/Ailbeche.lua#L17)

**Comment by Skerxan** [comment]
He did those steps several times and got the CS's.

**Comment by TeoTwawki** [comment]
```lua
    elseif (csid == 15 and player:getCharVar("aBoysDreamCS") == 3) then
        player:setCharVar("aBoysDreamCS", 4)
    elseif (csid == 47 and player:getCharVar("aBoysDreamCS") == 4) then
        player:setCharVar("aBoysDreamCS", 5)
```
do'em again. if he's multiboxing at all log ALL chars out, exit game and windower/ashita fully, log back on just the one, and try again. Coz that code does in fact work.

**Comment by Skerxan** [comment]
```
        if (trade:hasItemQty(17001, 1) == true and trade:getItemCount() == 1 and player:hasItem(4562) == false) then
            player:startEvent(15) -- During Quest "A Boy's Dream" (trading bug) madame ?
```

Found the problem. Because he had the Odontosaurus while being on var 3 prevented him from progressing.

**Comment by TeoTwawki** [comment]
Thing is tho, he shouldn't have that at that stage for it to interfere.

Was hoping you'd notice the bad code that says `>=` and lets players repeat steps they probably shouldn't while you were there.

Quest is due to get converted to the new system which will do away with the problematic bits.


Its screwy, but it is completable.
