### ISSUE TITLE
abyssea.lua ‘s bug 

### ISSUE THREAD

**Issue by zanglikun** [DerpyProjectGroup/topaz#17]
- [ ] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/DerpyProjectGroup/topaz/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
in xi.abyssea.qmOnTrade = function(player, npc, trade)  this code：

if #reqTrade == 0 or trade:getItemCount() ~= #reqTrade then
end

#reqTrade is always 8，It's not real. It's length ，so i think should check reqTrade'size
like this:

`	**local tablesize = 0
	for k, v in pairs(reqTrade) do
		-- v is itemID
		if(v ~= 0)then
			tablesize = tablesize + 1
		end
        end**
`
tablesize  is real reqTrade'size

and then validate traded items should avoid judgment of item 0
`    for k, v in pairs(reqTrade) do
	**if v == 0 then
		break
	end**
        if not trade:hasItemQty(v, 1) then
            return false
        end
    end
`
when trade in keyitem to spawnmob should do this 
`-- validate kis
    local validKis = true
    for k, v in pairs(kis) do
		**if v == 0 then
			break
		end**
        if not player:hasKeyItem(v) then
            validKis = false
            break
        end
    end
`

**Comment by zanglikun** [comment]
[abyssea.txt](https://github.com/DerpyProjectGroup/topaz/files/6338990/abyssea.txt)
like this

**Comment by claywar** [comment]
@zanglikun Have you implemented all of the commented out code?  This looks like a WIP that was never completed.

**Comment by wrenffxi** [comment]
reqTrade isn't the trade container.  It's the required trades, as defined in the Abyssea zone's IDs file.  Note that these are all commented out on stable branch because none of the NMs are implemented.

But for example if you were trading to Abyssea Grauberg's qm4 NPC, and that line were uncommented, reqTrade would be {3264, 3274}, therefore length 2, not length 8:
<https://github.com/DerpyProjectGroup/topaz/blob/allegedly-stable/scripts/zones/Abyssea-Grauberg/IDs.lua#L36>

~~I believe in past me getting this code right.~~  But let's double check.

uncommented qm4 in abyssea grauberg:
![image](https://user-images.githubusercontent.com/21246949/117899507-44425080-b295-11eb-8b7e-91bb6fc2a610.png)

print size of reqTrade:
![image](https://user-images.githubusercontent.com/21246949/117899576-66d46980-b295-11eb-9df5-7af24d14d072.png)

attempt the trade:
![image](https://user-images.githubusercontent.com/21246949/117899926-33460f00-b296-11eb-976a-f5cfd7516791.png)

Well, shit.  :D Issue is absolutely right.  Good catch!  Interestingly, I know this code used to work because I tested all the trades at the time I wrote it.  Will do some digging.

edit: AH!  Found the problem.  Fix incoming.  Issue was that the onTrigger infilled QM_POPs table with 0's while generating event parameters.  So if you triggered first, then traded, it bonked.
