### ISSUE TITLE
[chore] Audit packet construction

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#178]
While investigating my last issue, I noticed there are two different ways of assigning packet type and size.
We _should_ be using this way, due to `id` actually being 9 bits. 
We should also be assigning larger-than-8-bit numbers to really hammer this point home.
Perhaps also logging if we try to assign something too big to size.
Part of this could also be making the raw id and size fields be inaccessible etc.

```cpp
    // Set the first 9 bits to the ID. The highest bit overflows into the second byte.
    void id(unsigned int new_id)
    {
        ref<uint16>(0) &= ~0x1FF;
        ref<uint16>(0) |= new_id & 0x1FF;
    }

    // The length "byte" is actually just the highest 7 bits.
    // Need to preserve the lowest bit for the ID.
    void length(std::size_t new_size)
    {
        ref<uint8>(1) &= 1;
        ref<uint8>(1) |= ((new_size + 3) & ~3) / 2;
    }
```

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by atom0s** [comment]
Here's some client side packet construction information that may be of use that I've reversed over the years:

The client constructs the packet header in two stages when building outgoing packets (C2S) due to the way the internal buffer is handled and what rulesets are in place for how packets send and prevent spam.

Basic jist of how the client prepares to sends things is:

```cpp
auto packet = RequestPacketBuffer(id, param1, param2);
if (packet)
{
    // construct packet data here..

    QueuePacket(packet, size, align);
}
```

When the client requests a packet buffer, it passes the id and two params. The internal packet system in the client uses the id and the two params to determine how to return the 'proper' buffer, if any. The two additional params determine if a buffer is reused if a same-id packet is already queued, or if a the packet is ignored altogether due to an interal timer table that is used to delay and prevent spam of similar packets in a single 'tick'. The id is simply masked into the buffer during this step like this:

```cpp
void* RequestPacketBuffer(uint32_t id, int32_t param1, int32_t param2)
{
    // do other setup work here..

    uint16_t* packet = sub_PrepareBuffer(...);

    *(uint16_t*)(packet + 0x00) = id & 0x01FF; // Sets the id and size.
    *(uint16_t*)(packet + 0x01) = 0;           // Sets the sync count.

    return packet;
}

```

_Casting optional in this case, but left for easier understanding. Be mindful of the pointer type and the addition of +1 is actually moving two bytes etc._

Once the packet is prepared by the client with the appropriate data, it's then queued with its size and alignment params. This is when the packet header is rebuilt and validated. If fine, the internal packet system prepares the buffer to be queued for sending, or if it fails, the size and sync count is erased and the id is restored to allow the buffer to be reused later if possible. This looks like this:

```cpp
void* QueuePacket(uint8_t* packet, int32_t size, int32_t align)
{
    // Rebuilds the id and size in the header..
    const auto idSize = *(uint16_t*)packet & 0x01FF ^ (((size + align) / 4 + ((size + align) % 4 != 0)) << 9);
    *(uint16_t*)packet = idSize;

    // Validation steps..
    if ((idSize & 0xFE00) != 0 && 4 * ((uint16_t)idSize >> 9) <= 260)
    {
        /**
         * Packet is valid; adjustments to the internal packet buffer/queue is made for this packet.
         */
    }
    else
    {
        /**
         * Packet is invalid; the id is restored in case the buffer can be reused later, but the size and sync are reset to 0
         * to ensure the packet is not sent/used.
         */
        *(uint16_t*)(packet + 0x00) = idSize & 0x01FF;
        *(uint16_t*)(packet + 0x01) = 0;
    }

    return packet;
}
```
Due to this alignment, it means that, by default, the packets are 4 byte aligned. XI also 'halves' the packet size to have it fit into the packed id/size data. For example if you were to attempt to queue 33 chat packets, ranging from sizes 0 to 32, this is how the handler would align their size/header info:

```
Size:  0 -- Packe Header: 000A -- Packet here is considered bad, so the size/sync is wiped.
Size:  1 -- Packe Header: 020A
Size:  2 -- Packe Header: 020A
Size:  3 -- Packe Header: 020A
Size:  4 -- Packe Header: 020A
Size:  5 -- Packe Header: 040A
Size:  6 -- Packe Header: 040A
Size:  7 -- Packe Header: 040A
Size:  8 -- Packe Header: 040A
Size:  9 -- Packe Header: 060A
Size: 10 -- Packe Header: 060A
Size: 11 -- Packe Header: 060A
Size: 12 -- Packe Header: 060A
Size: 13 -- Packe Header: 080A
Size: 14 -- Packe Header: 080A
Size: 15 -- Packe Header: 080A
Size: 16 -- Packe Header: 080A
Size: 17 -- Packe Header: 0A0A
Size: 18 -- Packe Header: 0A0A
Size: 19 -- Packe Header: 0A0A
Size: 20 -- Packe Header: 0A0A
Size: 21 -- Packe Header: 0C0A
Size: 22 -- Packe Header: 0C0A
Size: 23 -- Packe Header: 0C0A
Size: 24 -- Packe Header: 0C0A
Size: 25 -- Packe Header: 0E0A
Size: 26 -- Packe Header: 0E0A
Size: 27 -- Packe Header: 0E0A
Size: 28 -- Packe Header: 0E0A
Size: 29 -- Packe Header: 100A
Size: 30 -- Packe Header: 100A
Size: 31 -- Packe Header: 100A
Size: 32 -- Packe Header: 100A
```

This allows the client to have:
  - A maximum packet id of: `511` (9 bits)
  - A maximum packet size of: `508` (7 bits)

_The client aligns the buffer for each packet to 512 for the alignment etc. but only 508 bytes are usable._

Some other notes in regards to the client packet handling:

  - The client is hard-coded to validate certain size information.
  - The minimum packet chunk size allowed is 45 bytes. (Compressed size.)
  - The maximum packet chunk size allowed is 1360 bytes. (Compressed size.)
  - The maximum packet id allowed (as of today) is 287. (S2C)
  - The highest packet id the client seems to send (as of today) is 285. (C2S)

I'd assume the 1360 limit is due to an agreed baseline for what FFXI could handle back when it still was mainly played on dial-up/DSL. It's more of a happy high-end on the MTU limit, just below DSL's suggested maximum, but still being higher than 56k's recommended. I'd assume heavy testing during the beta showed them what both 56k and the PS2 could handle in regards to decoding speeds and such to come up with that number. _(This would suggest that SE has their MTU designed for 1400, as the IP headers and such would take up the other 40 bytes equaling out to 1400.)_

As for the `align` param to the `QueuePacket` function above, this is used when strings are being used inside of the packet. This tells the packet how to align to the 4-byte bounds.

Packets currently using this param are:

  - 0x00B5 - Align is to the message string length. (Null terminator removed.) (Maximum string size of: 150)
  - 0x00B6 - Align is to the message string length. (Null terminator removed.) (Maximum string size of: 150)
  - 0x00B7 - Align is to the message string length. (Null terminator removed.) (Maximum string size of: 150)
  - 0x001F - Align is to the message string length. (Null terminator is kept.) (Maximum string size of: 150)
  - 0x001E - Align is to the message string length. (Null terminator is kept.) (Maximum string size of: 150)
  - 0x001E - Align is to the message string length. (Null terminator is kept.) (Maximum string size of: 150)
  - 0x0075 - Align is to the message string length. (Null terminator is kept.) (Maximum string size of: 249)
  - 0x00A0 - Align is to the message string length. (Null terminator is kept.) (Maximum string size of: 151)
  - 0x00A1 - Align is to the message string length. (Null terminator is kept.) (Maximum string size does not appear to be clamped.)
  
All of which are using it with `strlen( )` and adjusting the returned length accordinly if clamped, if removing the null char, etc.

**Comment by zach2good** [comment]
Done in https://github.com/LandSandBoat/server/pull/1255
