### ISSUE TITLE
onSpikesDamage function causes spikes effect to trigger twice

### ISSUE THREAD

**Issue by CriticalXI** [DerpyProjectGroup/topaz#1792]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Attacking a mob using the `onSpikesDamage` function causes the spikes to apply twice to the attacker.

## Expected behavior

Spikes damage only hurts the player once per swing. 

![image](https://user-images.githubusercontent.com/48370698/169923477-8eb05e17-3d03-4b47-a2e9-aa116f0f211b.png)

**Comment by RAIST5150** [comment]
Hmmm... have yet to experience this on xiweb.  Just watched a fight against an eschan phuabo, and the chat log only saw spikes damage proc once per hit... both from mob to player/trust and player/trust to mob (on SMN).

Not sure if they are making the same call or not... but it appears to be working right in that regard, at least on this job and this mob.

Could it be more mob or job specific?

Also, is the server this occurred on running current base?  

Xiweb is only a day or two behind, as it just updated this past weekend (Sunday iirc).

**Comment by CriticalXI** [comment]
To clarify, this is only for mobs using the function "entity.onSpikesDamage" in their lua to adjust the amount of damage the spikes are dealing to the player. I was running this on a branch that was created from `base`.

**Comment by TeoTwawki** [comment]
That damage value indicates the calculation is getting fubar'd too. it shouldn't be 45 every hit. Thats the base power for the status effect we piggy back to trip the script

(side note: I very much want to change with that. scripted perma spikes should not require this. its a pain because for some mobs you -can- steal or dispel their auto spikes with thf JAs.. This tells me SE used more than 1 method for auto spikes)

**Comment by TeoTwawki** [comment]
Repro's myself on 2 diff mobs. The status effect is processing, then the scripted spikes are processing. By design the scripted spikes should be replacing the damage and message of the status effect. Instead both are running at the same time, trying to send the client TWO damages and messages but they are so close together that the values for the status are the ones displayed.

Right now, if you delete the status effect off them neither spikes will happen (that is as intended at the time these were designed even tho I dislike that).

If you comment out the onSpikesDamage function instead, you will get 1 spikes damage and one message, however the power/damage of that spikes hit will be wrong. It won't be calculated at all - it'll just do exactly the damage number in the addStatusEffect line of the script instead.

**Comment by TeoTwawki** [comment]
Can anyone check if  #3743 happens to correct this? It was made to fix something else but may have hit this in the same go.

**Comment by CriticalXI** [comment]
I can confirm this has fixed the double proc with the same mob in the example above. Looks good now!

![image](https://github.com/LandSandBoat/server/assets/48370698/fd5ba478-3e81-4a3c-943d-b55d0b0c4415)
