### ISSUE TITLE
Cannot Use Scroll of Regen V

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1930]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Have SCH 99 as main job
2. Ensure character does not know the Regen V spell yet
3. Try to use a **Scroll of Regen V** on yourself
NOTE: You will get the message _"You cannot attack that target_".

## Expected behavior

The character uses the scroll, without error, and learns Regen V

**Comment by ghost** [comment]
I can say I have tested this and I was able to cast Regen V on Sch 99 as long do !addallspells

But trying to use the scroll it does give error You cannot attack that target.

At this time 75+ content is been worked on, but mention this issue sure someone be able to work on a fix

**Comment by RAIST5150** [comment]
Doesn't appear to be fully implemented yet on base.  Did not spot proper entries in the globals/items folder, nor item_usable.sql.  Such missing pieces will need to be generated appropriately to use the scroll to learn the spell.

Guessing all that wasn't completed because the normal methods to obtain the scroll is from more advanced content (Voidwatch III, Legion, Meebles...), and SCH is still in a bit of a WIP state as well.

**Comment by Dev-Roland** [comment]
It appears that this has been resolved by https://github.com/LandSandBoat/server/pull/1934. I confirm that I was able to learn the scroll ingame today.
