### ISSUE TITLE
Implement `Ruszor` mob skills, because BLU spell `Sub-Zero Smash` is not learnable

### ISSUE THREAD

**Issue by mrhappyasthma** [DerpyProjectGroup/topaz#201]
The skill exists in the sql tables, but there is no Lua implementation, so the mob never casts it.

The other skills for the mob, so that the `sub-zero smash` is not cast 100% of the time.

**Comment by mrhappyasthma** [comment]
Still need to implement:

1. Aqua Blast (in progress!)
2. Frozen Mist
3. Hydro Blast
4. Hydro Wave

**Comment by Xaver-DaRed** [comment]
Maybe this can help you finding some information on this family mob skills:

https://55qyrhg5xpivgc2vfqirnmj7bu-adv7ofecxzh2qqi-wiki-ffo-jp.translate.goog/html/17683.html

JP Wiki. It lists Mob skills, each has "some" info

**Comment by ampitere** [comment]
It doesn't seem like Hydro Blast is a real skill? Or at least I can find no information about it.

**Comment by mrhappyasthma** [comment]
I think it was a translation error from the jp resource. I suspect Hydro Blast was a mistranslation of Aqua Blast.

**Comment by ampitere** [comment]
> I think it was a translation error from the jp resource. I suspect Hydro Blast was a mistranslation of Aqua Blast.

https://ffxi.gamerescape.com/wiki/Hydro_Blast
https://ffxiclopedia.fandom.com/wiki/Hydro_Blast

Yeah I commented that I couldn't find anything then found some documentation, but it's all old stuff and it seems like a translation error since captures don't have them using it either. BG-wiki and the JP wiki both do not have the skill listed either.

[Beaucedine Glacier [S].log](https://github.com/LandSandBoat/server/files/15312781/Beaucedine.Glacier.S.log)

**Comment by ampitere** [comment]
https://docs.google.com/spreadsheets/d/1YBoveP-weMdidrirY-vPDzHyxbEI2ryECINlfCnFkLI/edit#gid=57955395

It's also listed on here which confused me a bit, and it has some of the effects mixed up.
