### ISSUE TITLE
🐛 Windower: GearSwap's Aftercast Delayed on Nuke Demotion

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#2066]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Load Windower with GearSwap
2. Set player's job to BLM, SCH, RDM, or GEO (for nuke availability)
3. Load a GearSwap job.lua that has diverse gear in the pre/mid/after cast for elemental nukes
4. Load the [NukeDemoter ](https://github.com/Roland-J/Windower-Addons/tree/main/NukeDemoter) addon
5. (Optional) Input the _"//nd debug"_ command to see additional context from NukeDemoter when nuking
6. (Optional) Input the _"//gs showswaps"_ command to see additional context on GearSwap equip swaps
7. Travel somewhere where multiple mobs can be found in close proximity to each other (suggestion: Misareaux Coast homepoint)
8. Cast Thunder 5 2x in a row, without allowing the spell's recast to renew itself
9. **On the first cast** (Thunder V), note that the aftercast is equipped immediately after the spell completes casting
10. **On the second cast** - _Thunder V demoted to Thunder IV_ - note that the spell was demoted to the previous tier
11. **On the second cast** - _Thunder V demoted to Thunder IV_ - note that the aftercast is delayed to when Thunder V (original spell) would have completed rather than when Thunder IV (final spell) completed.

**NOTEWORTHY:**
- Repeat steps 1-11 above on retail to note that aftercast is not delayed on step 11 when in retail _(LSB-esclusive symptom)_
- Cast the demoted spell on its own in LSB, without demoting into it from above, and notice that its aftercast is equipped at the appropriate time _(demotion-exclusive symptom on LSB)_

## Expected behavior

The aftercast occurs according to the timing of the final spell rather than the original spell.

**Comment by Dev-Roland** [comment]
A video demonstration

https://user-images.githubusercontent.com/106891580/174851693-79162b13-7c8c-4214-9ad1-67948aa4962f.mp4

.

**Comment by Dev-Roland** [comment]
Tagging to other issue: https://github.com/LandSandBoat/server/issues/2019

**Comment by WinterSolstice8** [comment]
I found some time to test this, to me I _never_ get aftercast. I think your lua might "know" how long the spell should take and swap back (this is useful if you get stunned, petrified, silenced, etc). 

I tested with Banish though, just reused the WAR/WHM half baked setup I made for the previous test.

Very weird. Will dig...

**Comment by WinterSolstice8** [comment]
The packets check out, however...

I can produce this on retail (limited testing, I spent longer trying to understand gearswap's systems), and this looks like that addon is modifying the action after gearswap thinks you're going to try to cast the same spell again

In gearswap's Flow.lua, find this line (around line 141):
`ts = command_registry:new_entry(val1)`
add:
`windower.add_to_chat(4,tostring(val1.en))`

reload gearswap, then try casting Fire 5 twice in a row, it should say Fire V, Fire V. (this indicates it's taking your command from your text input box, aka outgoing text which is how all commands are parsed even though macros, etc)

Also, edit your gearswap.lua, near the top here, around line 32:

```
if windower.file_exists(windower.addon_path..'data/bootstrap.lua') then
    debugging = {windower_debug = true,command_registry = false,general=false,logging=false}
else
    debugging = {}
end
```

to

```
if windower.file_exists(windower.addon_path..'data/bootstrap.lua') then
    debugging = {windower_debug = true,command_registry = false,general=false,logging=false}
else
    debugging = {command_registry = true}
end
```
you'll now see a message on the second cast:
`Hitting Aftercast without detecting an entry in command_registry`
My suggestion is to raise an issue on windower, to possibly add an `equip_sets` call to that fallback because it can't catch modified outgoing packets. The alternative is the editing that addon so that it changes the outgoing text (Check Gearswap's Trigger.lua for Outgoing Text hook to see how they read it.) Gearswap does read the _modified_ outgoing text, so you'll be fine there.

P.S.: I am pretty sure that gearswap was designed to read the outgoing text intentionally so it could modify it directly (for target switching reasons among other things).

I also do have a nuke demotion code for my BLM luas (based on motes), as follows. This could solve the problem immediately for you:

I think I got all the functions, but let me know if I missed something.
[mote_degrade.txt](https://github.com/LandSandBoat/server/files/8973578/mote_degrade.txt)

**Comment by WinterSolstice8** [comment]
Actually, I think i'll just make a PR to update gearswap instead.

**Comment by WinterSolstice8** [comment]
https://github.com/Windower/Lua/pull/2199

**Comment by Dev-Roland** [comment]
I had not mentioned this yet, but I had Xaver test this with the same [GS files](https://github.com/Dev-Roland/Temp-For-2066) as I have and Xaver got aftercast on retail **with NO delay** and aftercast on LSB **with** delay, which I would guess indicates a delta in that that retail sent his client a packet after finishing the cast - _that GS used to trigger aftercast_ - that LSB isn't sending; Xaver stated that retail was spamming packets to his client when the spell finished. So this may be more than just a GS issue.

As for degrading in a GS job.lua, I also know how to do so, however the whole reason I created this addon was to centralize it and strip all dependencies to GS and job.luas thereby making the addon more universal, easy to use, and user friendly.
Methods: (From best to worst IMO)
1. Centralized addon _(I've not found a single person that did this. Super user-friendly. Seems to work fine in retail.)_
2. Centralized GS library _(Mote didn't do this. It's easy enough to do but some may be nervous about going in the libs.)_
3. De-centralized code that must be added to every job.lua _(Most people do this. Least user-friendly and most repetitive.)_

As for modifying the outgoing text for GearSwap, I have a feeling that is a losing battle due to potential addon load order conflicts and the lack of control over the addon load order.

It seems like finding out what's causing the delta in retail vs LSB, and seeing if it could be fixed, may be a good solution.
However, if you've found a way to wave your magic wand and get GearSwap to honor the changed parameter, that may be the best solution! _(Hopefully leaving the packet delta in place doesn't cause any issues down the road. I don't know how many other addons rely on these packets that seem to be missing.)_

**Comment by WinterSolstice8** [comment]
Works for me.
