### ISSUE TITLE
🐛 Capped at Lv1 after switching to Limit Points mode

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#2511]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

After switching to limit points mode on my 75 job, then to a level 1 job, I was capped at level 1
Fixed by returning to my 75 job and switching to exp mode 

![image](https://user-images.githubusercontent.com/65316697/184428240-3b964426-6dea-4bfa-b6cb-b460187455f1.png)

## Expected behavior

Should not be capped

**Comment by SirGouki** [comment]
Actual expected behavior: Limit mode should be toggled off when a job is changed to a non-maxed job.  From the screenshot, it is obvious that limit mode is still on (level is blue instead of the normal font color).

Work around: manually toggle off limit mode before switching jobs from a 75+ to a not 75+.
