### ISSUE TITLE
🐛 Cant Trade Jugs

### ISSUE THREAD

**Issue by Zofra2020** [DerpyProjectGroup/topaz#2642]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

item- Broth Jug

`base`

## Steps to reproduce
I bought stack of 12 jug broth, equipped it, then unequip it and split the stack. Then I equipped the stack that I keep then it wont let me trade the remaining broth. So, I have to unequip then I can trade this remaining broth. Tested with other kind of broth, seems its linked with all jugs or ammos? I put the broth in Wardrobe to split stack btw.

![cantrade](https://user-images.githubusercontent.com/40586417/188228779-b937a936-aeb8-4cdb-94bc-90e220a94610.jpg)
![cantradeherbal](https://user-images.githubusercontent.com/40586417/188228781-83c39285-8170-4e7b-9ba5-07625e49538c.jpg)
![canttrade](https://user-images.githubusercontent.com/40586417/188228782-6248f1f8-9d4a-4a70-a68b-c933fcbb04a3.jpg)
![canttradeherbal](https://user-images.githubusercontent.com/40586417/188228784-5786f5b4-a2bc-4671-aaec-2cf4592e339b.jpg)
## Expected behavior
Should be able to trade while having partial stack equipped?

**Comment by SirGouki** [comment]
Most of these jugs have the flags = 2052.  This means they are equipable, and can be mailed to the same account, but they are NOT RA/EX.

Is there somewhere else I can check for trade blocking?

EDIT3: I repeated the test conditions with carrot broth listed in the OP.  I have a partial stack of 6 equipped (grayed out in first trade ss), and another partial stack of 6 unequipped (orange in same ss).  I was able to add the unequipped pstack to the trade.  NOTE: I used manual sort to move the unequipped partial stack up the list so they'd be next to each other
GM:
![image](https://user-images.githubusercontent.com/11664236/190503150-ad5636a4-0a81-41eb-8d12-0905c822c5b5.png)
Trade target:
![image](https://user-images.githubusercontent.com/11664236/190503260-7d11264b-ebd9-4c64-ab60-eddf164d28da.png)
Finished trade (there's 8 because I traded 2 singles prior to this):
![image](https://user-images.githubusercontent.com/11664236/190503635-8989bb59-81df-4846-9628-ffbc5404d66f.png)

I tested this twice, the screen shots are from just having 2 pstacks of 6 in the inventory, one equipped and the other not.  The second test I performed was with an equipped pstack of 3 in the wardrobe 1, and the remaining 3 in my inventory.  This also worked with no issues.
This was either fixed since it was posted, or there's something else going on here

**Comment by SirGouki** [comment]
I'm making this a second comment to seperate the content:

@Zofra2020 Just in case, you can not trade from Wardrobe, it has to be in your inventory.  the way you worded this:
```I bought stack of 12 jug broth, equipped it, then unequip it and split the stack. Then I equipped the stack that I keep then it wont let me trade the remaining broth. So, I have to unequip then I can trade this remaining broth. Tested with other kind of broth, seems its linked with all jugs or ammos? I put the broth in Wardrobe to split stack btw.```

Seems to indicate you moved some into wardrobe, then equipped what was in your inventory (I equipped the stack that I keep), and if thats the case, this is user error on your part.  You'd have to equip the ones in your wardrobe (when you select the slot press up once and accept and it'll let you select the storage from where you want to equip, if you didn't know)  Your screen shots indicate that this is the case since both broths in the 2nd pair of shots are grayed out.  This is working as intended because you equipped them from your inventory instead of your wardrobe, and items in your wardrobe will not show up in the trade as thats whats in your inventory.

**Comment by Zofra2020** [comment]
I did double checked, yes you are correct.  I must have equipped the inventory broth and trying to trade the wardrobe broth.  I guess I forgot to change to wardrobe option while equipping the broth.  Thanks for clearing this up!
