### ISSUE TITLE
MDT/PDT isn't using x/256

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#266]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: current

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Retail uses x/256 for MDT and PDT, it's not being used and all DT is just standard numbers besides breath which is using /256.

https://github.com/LandSandBoat/server/blob/094ec9f022916bc86b8d0efee166b626ec560c2c/src/map/utils/battleutils.cpp#L4920

http://wiki.ffo.jp/html/1714.html
https://www.bg-wiki.com/ffxi/Damage_Taken

**Comment by TeoTwawki** [comment]
This (not being 256 based) is not a bug, it was intentionally changed from using 256 because it was a massive pain in the rear that everyone got wrong. The difference is negligible. All of them should just be using additional decimals of precision for when we need to be more precise. Remember we're trying to _emulate_ what its like on retail, not do precisely the exact things SE did to arrive at it. I cannot find the exact commit right now, but the older devs moved away form x/256 a long time ago, and after doing the math the difference was almost always shaved off by truncation or rounding anyway.

**Comment by TeoTwawki** [comment]
the folks that did it should have documented WHY they did it so I wouldn't ever have to see that debate again. :rage:  (I'm mad at the lack of documenting, not you)

**Comment by TeoTwawki** [comment]
This was also done with haste, which I am able to find the history for: https://github.com/DarkstarProject/darkstar/pull/5174


edit: the line I linked in the old dsp pr, I did not link to the revision at the time so it no longe rpoints to the correct line of code...

it was changed from: `1.0f + ( floor( 256.0f * ( PDefender->getMod(Mod::DMGPHYS) / 100.0f ) ) / 256.0f )`

to: `1.f + PDefender->getMod(Mod::DMGPHYS) / 100.f + PDefender->getMod(Mod::DMG) / 100.f;`

because it turned out that _both calcs get the same result_

**Comment by TeoTwawki** [comment]
#659
While not moved to a 256, the additional bits of precision allow it to be accurate enough to satisfy most people
