### ISSUE TITLE
Error: No module named 'mariadb'

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#2955]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Running update today doesn't works for db anymore:

C:\server\tools>py -3 dbtool.py update
ERROR: Exception occured while importing external dependencies:
No module named 'mariadb'

**Comment by cocosolos** [comment]
As of #2947 there has been a switch from the MySQL Python connector to the MariaDB version. Please update your modules by running `py -3 -m pip install --upgrade -r requirements.txt` in your server/tools/ folder. If you're using Linux, use `python3 -m pip install --upgrade -r requirements.txt` instead, or whatever alias you use instead of `python3`.

**Comment by Gradius2** [comment]
Fixed.  Thanks.
