### ISSUE TITLE
🐛 Cure V giving twice as much enmity as it should

### ISSUE THREAD

**Issue by TracentEden** [DerpyProjectGroup/topaz#3016]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Bind a mob and check enmity then Cure V yourself and check enmity again

## Expected behavior
The enmity should be half of the given amount

I think the issue has to do with the enmity function being called from the cure_v lua. Basically the updateEmnityFromCure function in cure_v.lua uses 65535 as a dummy value for the cure amount which then sets a isCureV flag in the updateEmnityFromCure function in enmity_container.cc. This flag turns on hardcoded Cure V enmity values in updateEmnityFromCure. Thus the enmity is being counted from both the hardcoded enmity values in updateEmnityFromCure plus the fixed enmity values in spell_list.sql. This would explain the CE and VE values seen.

Solution I think would be to remove the updateEmnityFromCure function call from cure_v.lua or set the enmity values for Cure V in the spell_list.sql to zero.

Hopefully this is correct and makes sense!

(This also impacts ASB @The-Aerec)

**Comment by SirGouki** [comment]
This may be accurate, as when I fixed this during the live stream, I corrected the calculation in Core, I didn't touch the lua for it, (see  https://github.com/LandSandBoat/server/issues/814 )and I'd noticed it was a little on the high side when using `!getenmity`.

I'd initially thought it was accurate because of other factors during testing such as me hitting the enemy and casting multiple cures to make sure it was adding the same amount every time.  I knew the core fix was correct because I did real time debugging on it (added the variables in the calculation to quick watch, set break points so I could see the values).  

Note: during my testing of the aforementioned fix, it wasn't twice as high, but it was noticeably higher (it was around 100-200).

Edit2: Double checked this, this is actually the function in the core that I corrected the equation in, problem may be elsewhere as the equation in there works as expected.  See: https://github.com/LandSandBoat/server/blob/a400e68914cd8cc96b75b547441212d492e7b279/src/map/enmity_container.cpp#L243-L282

**Comment by TracentEden** [comment]
Yeah, both mechanisms have valid values (the hardcoded enmity values in updateEmnityFromCure and the fixed enmity values in spell_list.sql), but the issue is that both are being used. They were introduced into LSB around the same time but independently.

**Comment by SirGouki** [comment]
If what you're positing is true, then ALL cure spells are effected by this, not just Cure V.  This is because the else on the "If cure v" check is also using nothing but hard coded values, its just getting them from elsewhere (GetEnmityModCure is in battleutils.cpp, its not pulling anything from the DB either). See: https://github.com/LandSandBoat/server/blob/a400e68914cd8cc96b75b547441212d492e7b279/src/map/utils/battleutils.cpp#L422-L434

Not 100% certain where CureAmount is being gotten from, as I'm currently tracking everything down with notepad++ search functions, and none of the cure scripts pass this in.

Not seeing anywhere these are pulling the data from the DB either.  It's possible those values were intended to replace the hardcoded ones at some point, and never switched over.

Note: none of this is to disprove what you're saying, I'm simply noting what I find as I investigate the cause.

**Comment by TracentEden** [comment]
The enmity of cure I-IV is just based on the cure amount (do not need any other values, see https://kanican.livejournal.com/30142.html) and in spell_list.sql the enmity values of cure I-IV are set to zero (since they need to be calculated from the cure amount and thus cannot be fixed values) and thus are not double counted.

The cureAmount of cure spells I-IV are calculated in the cure_x.lua files. For example, in the cure_iv.lua file the cure amount is calculated and passed to caster:updateEnmityFromCure(target, final). The amount then passes through several functions until it reaches CEnmityContainer::UpdateEnmityFromCure for the actual enmity calculation.

Cure V is different in that the enmity is not based on cure amount but on fixed values.
