### ISSUE TITLE
Lag for level up animation

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#344]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This is an old issue but wanted to make a note of it here.

When you fight an enemy and you level up, it takes a couple seconds from the moment the enemy dies until you get the level up animation

**Comment by zach2good** [comment]
I noticed this the other day and I assumed it was because I was now using XIPivot and the big Ashenbubs dats. So it's not just me, thanks for reporting!

**Comment by RAIST5150** [comment]
Would add it also happens with merit and job point animations.

**Comment by claywar** [comment]
I feels like we're sending the level up animation aligning with some sort of tick.  It also differs from retail in that that animation is displayed on all level up events (it'll queue them as well).  For example, gaining a level outside of combat on retail doesn't display the message.

**Comment by TeoTwawki** [comment]
this can happen on retail as well, but usually it happens on exp sources other than direct mob death (book page exp causing level up notably is very delayed)

due that I must ask the exp source involved. If direct mob death exp is resulting in a lagged animation, that's a new problem that didn't exist in the past and cause for concern. otherwise it sounds like an old problem where it'd be nice to be "better than retail :)" but not really a priority.

**Comment by zach2good** [comment]
I noticed a delay with regular killing of mobs exp

**Comment by TeoTwawki** [comment]
k somethin def gone funky then
