### ISSUE TITLE
🐛 erroneous teleport menu prompt in Alzadaal Undersea Ruins

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#3976]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
windows server 2022

## Branch affected by issue 
`base`

## Steps to reproduce
go to "the room where get the cs for TOAUM 9" and trigger the teleport in the video. watch it keep prompting at the other side as in the video. I didn't get the positional coordinates from the player for this and haven't yet been in game to get them, but I presume these can be found in the related script anyway. 

https://github.com/LandSandBoat/server/assets/6871475/8dc2504a-2fb6-4379-8a35-6c233463b38e

## Expected behavior
not get teleport prompts at the landing site (misplaced `triggerArea()`?)

**Comment by Xaver-DaRed** [comment]
To add further:
`!pos 436.414 0.05 -552.659 72`

Will place you at first teleporter in the video.

This ONLY happens when taking that concrete teleporter.

Added prints to each region...
![imagen](https://github.com/LandSandBoat/server/assets/60053999/982f0b3a-a664-4803-a510-489ae945b653)

Final edit:
Regions 10 and 23 are conflicting with each other. I do remember now that a region can't be located inside another region.
