### ISSUE TITLE
🐛 Critical SQL Errors in World Server After LSB Merge

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4135]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
![image](https://github.com/LandSandBoat/server/assets/65316697/f26848ea-f1f2-4241-b6de-f092fd01e8ca)

Last commit: [f3aff01de24e86f5649842d86ff51f0322b67529](https://github.com/CatsAndBoats/catseyexi/commit/f3aff01de24e86f5649842d86ff51f0322b67529)

Rebuilt and Ran DBTool normally, was prompted for migration, which I accepted.

## Expected behavior

Should not error

**Comment by zach2good** [comment]
Do you know which LSB commit you had in terms of changes to the world server?
https://github.com/LandSandBoat/server/commits/base/src/world

My guess is it's the one from Feb, so the issue came in in one of (or all of):
https://github.com/LandSandBoat/server/commit/efa188386304e87c09cc50635db0afdf74e5685e
https://github.com/LandSandBoat/server/commit/6a2950c4482f2645394185c3eda3015496c49871
https://github.com/LandSandBoat/server/commit/7e5a982eb88aae8de8dcfbb3e392b8b16e1ec461

This one is just adding notes and no code changes:
https://github.com/LandSandBoat/server/commit/9484efcfbaf00140c6d26bd439a35a4a18564cf2

If that's the case, then the query is generated here:
https://github.com/LandSandBoat/server/blob/base/src/world/message_server.cpp#L144-L156

**Comment by zach2good** [comment]
I see the issue:
```
            uint32 partyid                        = ref<uint32>((uint8*)extra->data(), 0);
            ref<uint32>((uint8*)extra->data(), 0) = sql->GetUIntData(2);
            ret                                   = sql->Query(query, partyid, partyid);
```

Trying to get information from the query before we've executed it, innit.

@xkoredev did you test the new conquest system with parties/alliances?

**Comment by zach2good** [comment]
@CatsEyeXI while I'm looking into what this logic that writes back to the `extra` ZMQ data is doing, you can just remove or comment out `ref<uint32>((uint8*)extra->data(), 0) = sql->GetUIntData(2);` and everything should go back to normal

**Comment by CatsEyeXI** [comment]
> 

thank you will try that now.

**Comment by CatsEyeXI** [comment]
> @CatsEyeXI while I'm looking into what this logic that writes back to the `extra` ZMQ data is doing, you can just remove or comment out `ref<uint32>((uint8*)extra->data(), 0) = sql->GetUIntData(2);` and everything should go back to normal

This got rid of the errors, thanks.
