### ISSUE TITLE
🔨 Patching system (.diff) for core objects that cannot be modularized

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#4176]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

Not all objects can be patched in the core using cpp modules. I've improvised on Catseye by creating diff patches (with TortoiseGitUDiff) and applying them to the repo root. This is a tedious manual process. I'd love it if 'xit' or 'dbtool' had a way of sequentially applying these diffs. I was considering trying to add this functionality but I wanted upstream's input on whether or not this would be a worthwhile endeavor, or if this is something better kept in house.

Example: 
![image](https://github.com/LandSandBoat/server/assets/65316697/52669c92-2b7b-454e-8622-449ff6495fd0)

![image](https://github.com/LandSandBoat/server/assets/65316697/7f52be42-343a-48bd-aea8-0c23342d11ed)

**Comment by zach2good** [comment]
A quick summary of what we're talking about internally:

Diffs are super fragile and will break at the slightest change to the underlying file. Modules are fragile in that way too, but they won't die on whitespace changes etc. So, we're extremely unlikely to entertain legitimising a workflow that encourages diffs. Another reason we don't like them is that they modify the underlying file tree and will 100% lead to accidental check-ins of changes. No bueno.

HOWEVER. We've come up with a bunch of criteria that might help you get the things that you need to be supported upstream so you don't have to do this dance with rogue diff files:
- Is it a system that is needed _somewhere_ in retail? ie. global targetting is needed by _actual_ Domain Invasion and Dyna-D, so that could be submitted.
- If it isn't performance critical (https://github.com/LandSandBoat/server/wiki/Development-Guide-General), could you replace that code with a Lua binding, make it a function attached to the global xi object, and then modulize it? The long-term vision for the project is to move all gameplay logic that isn't performance critical into Lua for readability and ease of development. This comes with the bonus that it's then also easier to customise.
- If it's an _obvious_ improvement on retail (Not cheesing Trusts getting healing ticks for free while another Trust has enmity, for instance), slap it behind a setting, as I've already done with `ENABLE_TRUST_CUSTOM_ENGAGEMENT`

_Hopefully_ that covers the majority of your use cases?

**Comment by zach2good** [comment]
All the points in my summary still stand. TLDR; anything that is likely to want to be customised is probably valid to be ported up into Lua and then modularized, or tweaked using a setting. Anything beyond that is outside the scope of what we'd be willing to support
