### ISSUE TITLE
🐛 Magian DMG augments provide no benefit

### ISSUE THREAD

**Issue by MowFord** [DerpyProjectGroup/topaz#4853]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Currently, magian augments give augment ID 740, which has no mod mapping in the DB:

https://github.com/LandSandBoat/server/blob/0ced4398f975c776801619f82a0fd81fc22ea54d/sql/augments.sql#L899

Looks like it is probably due to lack of information on how exactly the augments are supposed to behave. I believe that all the calls to read the mod `DMG_RATING` (mod id 287) do so via the _weapon_ and not the _player_, so I'd imagine this should simply be adding mod 287, value 1 to augment 740 and 746 for melee and ranged weapon augments, respectively.

I would have made a PR but I don't have retail captures to back up what I _think_ the answer should be, so putting here for direction

## Branch affected by issue 

`base`

## Steps to reproduce

Give a weapon with a dmg augment (`!additem 18270 1 740 1`), then print `player:getWeaponDmg()` to see that it isn't getting any additional weapon damage

**Comment by TeoTwawki** [comment]
its been a long while (think way back in DSP circa 2016) but I think there was a need to figure out the differences in several seemingly duplicate DMG augments and determine if more than 1 modifier was needed - some discussion about 1 aug working on any item in any weapon slot ad another being only for an aug'd item in mainhand, and a few other questions.

Augments themselves apply directly to the item and not the player, so that parts covered at least.

Also I recall some of the caps seemed to only use an aug ID only on ranged or melee items, I'm not sure why ranged slot would need a different aug ID from melee - makes no sense to me.

**Comment by MowFord** [comment]
No idea on a different augment existing, as the game displays them them same:

![image](https://github.com/LandSandBoat/server/assets/131182600/c293e900-ca45-440e-9384-21a84f3a6b4e)

sounds like we should just do what I suggested and set augment 740 and 746 to give 1 `DMG_RATING` per tier of the augment

**Comment by TeoTwawki** [comment]
yeah they will all look the same, but SE had 3+ augment ids that display the same text. And then more for larger numbers than 1 at a time or starting above +32 (to get 33, 34, 35..)
