### ISSUE TITLE
[chore] Replace ShowMsg.h/.cpp with spdlog

### ISSUE THREAD

**Issue by zach2good** [DerpyProjectGroup/topaz#519]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Our logging system is all over the place. Some places seem to use `printf` format, some places seem to use `fmt` format, all logging is blocking and involves file access (!!!).

When I was doing my first few rounds of performance checking I noticed logs were taking **UP TO 8ms EACH!**.

I propose that we rip out the current system and replace it with `spdlog`. 
https://github.com/gabime/spdlog

**Comment by TeoTwawki** [comment]
so long as I can still do filtering for unwanted message logging, all for it.

Also I wanna say how dumb its always been that our logging has been in multiple near duplicate functions rather than making the type and colors parametrized, so this is a good way to fix that nonsense. He had the ability to do the main text and variables in separate coloring which is nice in the console but not used much, but even then that's just 2 more params in addition to type. didn't need to be a dozen functions, ya know? I didn't even realize we could get a performance boost ripping this out. Bonus points!
