### ISSUE TITLE
🐛 [Map.exe Crash] PUP Automaton in Instanced Zone

### ISSUE THREAD

**Issue by UmeboshiXI** [DerpyProjectGroup/topaz#5439]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base` (Unmodified LSB)

## Steps to reproduce

Go into an instanced zone (Nyzul if enabled,  or any assault) as a PUP. Spawn your automaton, then despawn it, then spawn it again right away. Notice that the grey name of your despawned automaton might stay after you respawn the next. The grey name does not go away. You will likely experience a map crash as well after respawning the automaton once or after a couple tries.

![image](https://github.com/LandSandBoat/server/assets/42159425/a973463c-7b32-4a38-bff5-210a7b156463)

[xi_map.exe_15-4_19-4-6.log](https://github.com/LandSandBoat/server/files/14986067/xi_map.exe_15-4_19-4-6.log)

## Expected behavior

Be able to summon Automaton without crashes.

**Comment by WinterSolstice8** [comment]
can't repro on linux? were there any other players? I tried on Lebros Caverns assault for a few mins

**Comment by UmeboshiXI** [comment]
I'll see if I can get a linux build set up tomorrow to test it again on there(I'm on Windows), need to make space on drive.

This was reported by a player on my server (Which is modified), they narrowed down the crash to this automaton issue. I then tested on a vanilla LSB build and was able to reproduce it there too. Latest client/build as of time of issue creation.

Did the despawned automaton's name ever go away for you? For me it always stays even after I summon a new one and usually crashes when there are 2 grey names. Its like something was not getting cleaned up.

(I'm in Nyzul floor 0 here, but I tested in other assaults with same result)
Example: 
![image](https://github.com/LandSandBoat/server/assets/42159425/7c6794a1-b19b-48de-883d-3dbfa1859128)

**Comment by WinterSolstice8** [comment]
Names didn't persist for me, no more than they usually do at least

**Comment by MowFord** [comment]
Did some testing (built on windows server)

![image](https://github.com/LandSandBoat/server/assets/131182600/d43eb804-03ac-441f-b0ce-552b1de95988)


![image](https://github.com/LandSandBoat/server/assets/131182600/904724b7-8f34-4df7-9038-4f6ce6bd0853)

https://imgur.com/a/MO2S8Zw

leftover automatons show as invalid targets when using `!checklocalvar`. They are still somehow in the server though because you can run 50 yalms out, come back in and they re-render

Unable to get it to crash reliably, but I'm also getting the same reports of pups getting nyzul crashes

Edit: here's a crash dump though

![image](https://github.com/LandSandBoat/server/assets/131182600/b30f52f3-87ee-407e-a56a-4c7492a54cda)

![image](https://github.com/LandSandBoat/server/assets/131182600/6cc62546-18b7-421b-9a40-91fdfcd37430)

**Comment by CatsEyeXI** [comment]
Dump:
https://drive.google.com/file/d/169SErulrDLzJfpJC_hTKvXU0KeP0U9FR/view?usp=sharing
