### ISSUE TITLE
docker container --outdated?--

### ISSUE THREAD

**Issue by lunacorn** [DerpyProjectGroup/topaz#547]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

server setup via docker 

using command
```
sudo docker-compose up
```

a few things i noticed was the inconsistency at connection which seems a docker issue upon my research so nothing we can do about that, unless i find a nice place to sleep it fora moment prior, still day 2 looking at this code.

however there are other issues with the db that i have not resolved yet

syntax error on DB_VER variable.  i hadnt seen where to locate this from the quick start guide so forgive the ignorance, is this an ENV i can set?

```
ERROR  1064 (42000) is the syntax error on line 13
ERROR  1146 (42S02) at line 1: 'xidb.DB_VER' doesn't exist  << comes from the tools\wait...launch.sh
```
i believe perhaps if thats resolved then line 13 on "wait_for_db_then_launch.sh" wont throw a syntax error, yea after checking pr and issues i hadnt seen reference to this.  super apologies if its a dup issue or resolution is elsewhere

if DB_VER is not the cause, then the startup throws a syntax error, on the db due to mariadb version, yet could not find a syntax problem at inspection.

**Comment by lunacorn** [comment]
forgive the double post forgot to mention that in the install 

```
DB_VER=`git rev-parse --short=4 HEAD`
echo -e "\n#DB_VER: $DB_VER" >> ../conf/version.conf
```

so i am curious if anyone is familiar with the docker container and can help me resolve this issue that my just be due to how its interacting with the server directory

**Comment by zach2good** [comment]
> outdated?

100%, none of the core contributors (or any downstream servers?) use our Docker setup/files for anything since it doesn't offer anything apart from a slow one-click setup.

We keep them around because every now and then someone pops up with an interest and leaves them looking a little better than when they found them.

Somewhat recently we made some changes to how `dbtool` ensures you're using it correctly, and it seems to clash with what docker wants. So the way to skirt around this is to remove the offending sections.

I just tested removing all of the `DB_VER` and `db_tool` sections out of `wait_for_db_then_launch.sh`, seems to be working fine:

Command to run: `docker-compose up -d --build`

`wait_for_db_then_launch.sh`
```sh
#!/bin/bash

while ! mysql --host=$XI_DB_HOST --port=$XI_DB_PORT --user=$XI_DB_USER --password=$XI_DB_USER_PASSWD $XI_DB_NAME -e "SELECT 1 FROM zone_weather LIMIT 1"; do
    sleep 5
done
sleep 5

# Start servers
echo "starting topaz_connect"
nohup ./topaz_connect > topaz_connect.log &
sleep 5
echo "starting topaz_game"
nohup ./topaz_game > topaz_game.log &
sleep 5
echo "starting topaz_search"
./topaz_search > topaz_search.log
```

Result:
![image](https://user-images.githubusercontent.com/1389729/127321583-dc63f665-a57f-4146-9780-daa886ba6338.png)

**Note:** all logs are dumped into `topaz_connect.log, topaz_game.log and topaz_search.log`

Good luck!

**Comment by lunacorn** [comment]
okay let us finish sorting a few things as we made a handful of adjustments... hoping to sort it so that it transfers easily to podman and docker is not vital for it.... yet seems we sorted the immeadiate issues, and happily will pr once its suitable

just due to desiring containerization / automation as much as possible on our server

**Comment by lunacorn** [comment]
what we currently have is container setup, proper db functions, and the capacity to cli from outside container backup/restore scripts in python3 ... so that it integrates with cron jobs or even discord bots etc
