### ISSUE TITLE
🐛 Getting warnings when compiling

### ISSUE THREAD

**Issue by Gradius2** [DerpyProjectGroup/topaz#5482]
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [X] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

OS: Windows11

## Branch affected by issue 

`base`

While compiling, I'm getting those warnings:

```
C:\server\build\x64-Release\_deps\efsw-src\src\efsw\Log.cpp(45): warning C4834: discarding return value of function with [[nodiscard]] attribute

C:\server\build\x64-Release\_deps\bcrypt-src\include\bcrypt\bcrypt.h(17): warning C4005: 'BCRYPT_HASHSIZE': macro redefinition

C:\server\build\x64-Release\_deps\bcrypt-src\src\bcrypt.c(32): note: see previous definition of 'BCRYPT_HASHSIZE'

C:\server\build\x64-Release\_deps\bcrypt-src\src\bcrypt.c(158): warning C4047: '=': 'char *' differs in levels of indirection from 'int'

C:\server\build\x64-Release\_deps\bcrypt-src\src\bcrypt.c(166): warning C4047: '=': 'char *' differs in levels of indirection from 'int'

C:\server\build\x64-Release\_deps\efsw-src\src\efsw\Log.cpp(45): warning C4834: discarding return value of function with [[nodiscard]] attribute
```

Microsoft Visual Studio Professional 2022 (64-bit) - Current version 17.9.6

All fully up to date.

**Comment by DCS78** [comment]
Similar issue here but errors rather than warnings. Running Visual Studio 2022 17.10.0 Preview 4.0 on Windows 11.

This started after I performed a from scratch rebuilt a week ago. First built 3 weeks ago. A commit in that period appears to have broken the build.

![Screenshot 2024-04-21 204236](https://github.com/LandSandBoat/server/assets/8366484/36c4ff09-e884-4980-bc56-b3810bc2289b)

**Comment by zach2good** [comment]
The warnings in the build are from external libraries we use (`efsw`, `bcrypt` and `maraidbcpp`), so we don't have much control over them.

@DCS78 if you have a problem with the build, please make an issue for your specific issue instead of piggybacking on this issue - which is about newly introduced warnings, not a broken build

**Comment by DCS78** [comment]
Thank you for the information. 
I ended up formatting the drive and starting from ground zero and it works again. Couldn't say where the error was introduced.

**Comment by Xaver-DaRed** [comment]
Not our issue, seemingly
