### ISSUE TITLE
infinity BCNM status somehow, at random

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#635]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

According to the player this happened to
> 6 accounts on multibox in same party in same area, horalis peak. Shattering stars maat fight attempts.
> Acc1 traded blm test entered, preceeded to win bcnm then left zone with warp after victory. Switched to access and noticed bcnm status still in effect. Clicked burning circle offered blm maat fight as an option without trading test.
>
> This occurred for all 5 remaining accounts.
Zoned, logged all 6 off waited 10 mins, logged back on and bc status still there, waited iver 30 mins and bcnm status still on. Clicking burning circle still gave bkm maat fight option without trading test. When tried to trade test said you must wait longer for this.
> 
> Sprinkles was trader
Appleshop, Brownie, Chocolate, Cake and Caramel were the other characters. Happened at Horlais peak around 4am bst(British Summer Time)

When I checked the database, this is what I saw:
![image](https://user-images.githubusercontent.com/6871475/130341591-bd8e7b47-b8f6-4dbc-a041-77bff82bae51.png)

I dunno how the F status got applied to them or why it landed with a zero duration.

I have exactly 3 spots different in my bcnm.lua, and that is simply to 
* comment out the GM getting all battlefields
* un-comment out the ACP battlefield in Qu'Bia area (its disabled on stock because the mobs skills need work) 
* and re-add the mission requirement that was deleted in DSP's refactor:
```lua
-- Those Who Lurk in Shadows (ACP7) disabled pending BCNM mob fixes
[ 532] = function() return (acp >= THOSE_WHO_LURK_IN_SHADOWS_III and player:hasKeyItem(xi.ki.MARK_OF_SEED)) end,
```
This happened to someone else several weeks prior to these edits also, further proving cannot be from an edit ***however***, I could reproduce it even on the same server where this happened. 
When I try to find how this happened it just..won't. (ノ°Д°）ノ︵ ┻━┻

This instance is different due to being a Maat fight. I didn't try it with a Maat fight before and perhaps I need to 6-box to make it happen. I can't really do that level of testing atm (overworked irl).

**Comment by TeoTwawki** [comment]
So now I have the same player tripping this entering limbus which has given us additional info to check things with: the key items aren't being taken from all characters, but they are all getting the status. And since limbus allows more characters than a Maat fight that rules out any shenanigans with the player count on entry.

> [1:29 PM] Apple Crumble: Mobs have parry/alliance hate and see all chars as party for hate and attack em even though unable to act on custard

Players appear to not all have been flagged for the battlefield, as they can't all act on each other despite obtaining BCNM status effect.

**Comment by AppleCrumble1** [comment]
6 chars on multibox entered limbus, only initial char has items removed (card and soap) others keep them over multiple entries. 
Upon entry trader (Custard) is unable to be buffed or healed by other party members, other 5 can all cast upon each other. All 6 have bcnm status icon at top of screen.

If Custard acts on a npc to engage in battle can fight as per normal, other 5 party members are able to perform an aggressive spell cast dia fire etc but the spell bar goes to 100% then disappears as normal but the spell does not land or appear in any logs on screen, though the spell still gains enmity on the npc. If other 5 party members initialises engagement upon npc the yellow mob turns red but no hits or spells do any actual damage or actually land but pull enmity from npc directed at said 5 players.

If custard dies and leaves the instance or warps etc out all mobs are removed from the limbus instance but the other 5 chars remain and can continue the climb through any remaining floors, all teleporter are unlocked and allow travel up through floors and culminate in normal exit on final floor, if the remaining 5 chars follow this route to leave bcnm status is removed as per normal finish of limbus. If the other 5 chars die, leave warp etc out bcnm status remains indefinitely and custard or other chars is/are unable to receive and buffs from the other 5 party members.
To have the indefinite bcnm status removed requires GM intervention. Though all 5 chars with bcnm status have been allowed to re enter limbus multiple times after due to not having card or soap removed, custard has always had to re-aquire the items.
Upon chatting with teo a few times regarding this issue we agreed for me to try a few things, I clicked the instance and entered 1 by one only when each char had fully entered, also to try to enter with minimum addons/plugins on ashita. 
![20211029_181832](https://user-images.githubusercontent.com/45308457/139494564-a08c21c7-bfe5-456a-a363-6d2da0c1b804.jpg)
Entered with the above addons and plugins and 1 by 1. The same issue persisted each time.

**Comment by AppleCrumble1** [comment]
Just installed windower and tried with that and exact same issue occurs, so has to be some code related problem for entry with multiboxing?. An other player on our server has entered fine with 3 chars.. no 8dea whats going on

**Comment by TeoTwawki** [comment]
I can't find the PR but I believe this was fixed, will reopen if I see it happen again.
