### ISSUE TITLE
King Vinegarroon agro when walking by

### ISSUE THREAD

**Issue by AppleCrumble1** [DerpyProjectGroup/topaz#713]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

Walking by KV he agros and begins to attack this is not normal behavior from retail, he is a passive NM.

**Comment by helixhamin** [comment]
`INSERT INTO `mob_pools` VALUES (2262,'King_Vinegarroon','King_Vinegarroon',274,0x00001C0100000000000000000000000000000000,1,1,7,280,125,0,**1**,0,0,2,0,32,661,159,0,0,0,0,0,274,274);`

This flag sets him as aggro (The one with double *'s, since I guess coding your stuff kills the formatting...). Basically, just need to set this flag to 0.

https://raw.githubusercontent.com/LandSandBoat/server/base/sql/mob_pools.sql

**Comment by TeoTwawki** [comment]
hence why `good first issue` tagged, as this low hanging fruit is a good easy pr for somebody

```sql
INSERT INTO mob_pools VALUES (2262,'King_Vinegarroon','King_Vinegarroon',274,0x00001C0100000000000000000000000000000000,1,1,7,280,125,0,FLAG_VALUE_HERE,0,0,2,0,32,661,159,0,0,0,0,0,274,274);
```

**Comment by CatsEyeXI** [comment]
#732

**Comment by helixhamin** [comment]
Fix merged. Should this issue be closed?
