### ISSUE TITLE
Free Divine Might Wins

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#739]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Steps to recreate:

1. Enter fight
2. Win or Die
3. Go back into BCNM and winning cutscene will play after opening cutscene
4. Go get earring

I confirmed this bug with another server operator.

**Comment by helixhamin** [comment]
Yes,  I found this when I died, that when I tried again, it just put me at the exit portal. I had to mess with some stuff to be able to re-enter the battle...

**Comment by GanimanSwift** [comment]
Can confirm this is a bug. You don't even need to win or die. If you disband the party after entering, all non party leaders will be removed from the battlefield and it is marked as a win. The party leader will not be ejected.

Edit: You can also enter, leave through the shimmering circle and re-enter to get a free win. This method also seems to get the battlefield status stuck, because the "re-enter" which triggers a winning cutscene moves out back out of the battlefield without cleaning up.
