### ISSUE TITLE
Nation Mission 5-2 doesn't reward KeyItem

### ISSUE THREAD

**Issue by Skerxan** [DerpyProjectGroup/topaz#787]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Several people have reported that they don't receive the Key Item "Shadow Fragment" after defeating the Shadow Lord.
We gave them the Key Item per command and the rest worked out.
This must have happened in one of the recent LSB updates?

`SHADOW_FRAGMENT = 74`
https://ffxiclopedia.fandom.com/wiki/Shadow_Fragment

https://ffxiclopedia.fandom.com/wiki/The_Shadow_Lord
https://ffxiclopedia.fandom.com/wiki/Xarcabard,_Land_of_Truths
https://ffxiclopedia.fandom.com/wiki/The_Shadow_Awaits

**Comment by RAIST5150** [comment]
Last discussion I recall, this was mostly isolated to a specific path because the Windurst track has not been converted to the interaction framework (a section is marked for deprecation after conversion).  At the time I (believe) San d' Orians and Bastokans were still able to get through it?

https://github.com/LandSandBoat/server/blob/base/scripts/zones/Throne_Room/bcnms/shadow_lord_battle.lua

**Comment by claywar** [comment]
@Skerxan Can you retest this with latest?  This should be resolved with the Windurst mission conversion.

**Comment by claywar** [comment]
Closing this issue, resolved by Interaction Framework rewrites for all nations
