### ISSUE TITLE
Missing support for "Nightmare" status effect

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#851]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://ffxiclopedia.fandom.com/wiki/Nightmare
https://www.bg-wiki.com/ffxi/Nightmare
https://www.bg-wiki.com/ffxi/Waking_Dreams

**Comment by MowFord** [comment]
adding to this as I plan on working on it soon:

https://youtu.be/NmhRM2KmIes?t=1218

video shows that Nightmare gives a sleep and bio buff

capture at the same time shows it's `SLEEP_I` and `BIO`

![image](https://github.com/LandSandBoat/server/assets/131182600/835cab41-c6ca-411d-8e5f-6fdf79a02d1a)

I've previously implemented this on wings and most of what I did should transfer just fine here:
- Make the "nightmare" ability apply a sleep that can't be broken by DoT and applies bio
- Make this Bio special in that it applies damage similar to helix (instead of regen_down), so we can pass a breakSleep=false flag

Edit: https://github.com/Wings-XI/LegacyWingsXI/commit/d1f6a0c10942318f5875a0dadc7e4e95e1c9bfe1 for reference
